<?php

namespace App\Services;

use App\Models\CallContext;
use App\Models\CallFlow;
use App\Models\CallQueue;
use App\Models\ConferenceRoom;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use App\Services\SipProvisioningService;

class DialplanService
{
    private string $extensionsPath = '/etc/asterisk/extensions.conf';
    private string $queuesPath = '/etc/asterisk/queues.conf';
    private string $featuresPath = '/etc/asterisk/features.conf';
    private string $confbridgePath = '/etc/asterisk/confbridge.conf';
    private string $marker = '; === AUTO-GENERATED BY Voxa Center ===';
    private string $asteriskConn = 'asterisk';

    /**
     * Regenerate extensions.conf, sync trunk contexts, reload Asterisk.
     */
    public function writeExtensions(): bool
    {
        try {
            // Build full dialplan from CallContexts (includes outbound routes)
            $content = CallContext::generateFullDialplan();

            // Add utility extensions to from-internal
            $content .= "\n; === UTILITY EXTENSIONS ===\n";
            $content .= "; Echo test (600) + AI test (601)\n";
            $content .= "exten => 600,1,Answer()\n";
            $content .= " same => n,Playback(demo-echotest)\n";
            $content .= " same => n,Echo()\n";
            $content .= " same => n,Hangup()\n\n";

            $content .= "\n" . $this->marker . "\n";
            $content .= "; Ne pas editer — gere par le Call Flow Builder\n\n";

            $flows = CallFlow::with('trunk')
                ->where('enabled', true)
                ->orderBy('priority')
                ->orderBy('name')
                ->get();

            // Group flows by inbound_context to combine filtered + default in same context
            $byContext = $flows->groupBy('inbound_context');

            foreach ($byContext as $ctx => $contextFlows) {
                $hasFilters = $contextFlows->contains(fn ($f) => !empty($f->caller_id_filter) || !empty($f->did_filter));

                if (!$hasFilters) {
                    // No filters — output each flow normally
                    foreach ($contextFlows as $flow) {
                        if (!$flow->trunk) continue;
                        $this->syncTrunkContext($flow);
                        $content .= $flow->toDialplan() . "\n\n";
                    }
                } else {
                    // Build combined context with routing logic
                    $firstFlow = $contextFlows->first();
                    if ($firstFlow->trunk) $this->syncTrunkContext($firstFlow);

                    $filtered = $contextFlows->filter(fn ($f) => !empty($f->caller_id_filter) || !empty($f->did_filter));
                    $default = $contextFlows->filter(fn ($f) => empty($f->caller_id_filter) && empty($f->did_filter));

                    $content .= "[{$ctx}]\n";
                    $content .= "; Auto-generated: combined context with Caller ID / DID filters\n";
                    $content .= "exten => _X.,1,NoOp(=== Inbound [{$ctx}] from \${CALLERID(num)} to \${EXTEN} ===)\n";
                    $content .= " same => n,Set(CDR(direction)=inbound)\n";

                    // Each filtered flow: build condition and Goto sub-context
                    foreach ($filtered as $flow) {
                        $subCtx = $ctx . '-flow-' . $flow->id;
                        $cidFilters = $flow->caller_id_filter ?? [];
                        $didFilters = $flow->did_filter ?? [];

                        // If both DID and CID filters: match DID first, then CID within sub-context
                        // If only DID: match DID
                        // If only CID: match CID
                        if (!empty($didFilters)) {
                            foreach ($didFilters as $did) {
                                $did = trim($did);
                                if (empty($did)) continue;
                                // Match EXTEN (the called number / DID)
                                // Also check with/without country prefix
                                $content .= " same => n,GotoIf(\$[\"\${EXTEN}\" = \"{$did}\"]?{$subCtx},\${EXTEN},1)\n";
                                // Try stripping leading 0 and matching +33 variant, or vice versa
                                if (str_starts_with($did, '0')) {
                                    $intl = '+33' . substr($did, 1);
                                    $content .= " same => n,GotoIf(\$[\"\${EXTEN}\" = \"{$intl}\"]?{$subCtx},\${EXTEN},1)\n";
                                    $content .= " same => n,GotoIf(\$[\"\${EXTEN}\" = \"0033" . substr($did, 1) . "\"]?{$subCtx},\${EXTEN},1)\n";
                                }
                            }
                        } elseif (!empty($cidFilters)) {
                            foreach ($cidFilters as $pattern) {
                                $pattern = trim($pattern);
                                if (empty($pattern)) continue;
                                if (str_contains($pattern, '*')) {
                                    $prefix = rtrim($pattern, '*');
                                    $len = strlen($prefix);
                                    $content .= " same => n,GotoIf(\$[\"\${CALLERID(num):0:{$len}}\" = \"{$prefix}\"]?{$subCtx},\${EXTEN},1)\n";
                                } else {
                                    $content .= " same => n,GotoIf(\$[\"\${CALLERID(num)}\" = \"{$pattern}\"]?{$subCtx},\${EXTEN},1)\n";
                                }
                            }
                        }
                    }

                    // Default flow (no filter)
                    if ($default->isNotEmpty()) {
                        $defFlow = $default->first();
                        $defSubCtx = $ctx . '-default';
                        $content .= " same => n,Goto({$defSubCtx},\${EXTEN},1)\n";
                        $origCtx = $defFlow->inbound_context;
                        $defFlow->inbound_context = $defSubCtx;
                        $content .= "\n" . $defFlow->toDialplan() . "\n\n";
                        $defFlow->inbound_context = $origCtx;
                    } else {
                        $content .= " same => n,Hangup()\n";
                    }

                    $content .= "\nexten => _+X.,1,Goto({$ctx},\${EXTEN:1},1)\n";
                    $content .= "exten => s,1,Goto({$ctx},0000,1)\n\n";

                    // Generate sub-contexts for filtered flows
                    foreach ($filtered as $flow) {
                        $origCtx = $flow->inbound_context;
                        $flow->inbound_context = $ctx . '-flow-' . $flow->id;
                        $content .= $flow->toDialplan() . "\n\n";
                        $flow->inbound_context = $origCtx;
                    }
                }
            }

            // Conference rooms — separate context included from from-internal
            $conferences = ConferenceRoom::where('enabled', true)->get();
            if ($conferences->isNotEmpty()) {
                $content .= "\n; === CONFERENCE ROOMS (ConfBridge) ===\n";
                $content .= "[conf-rooms]\n";
                foreach ($conferences as $conf) {
                    $content .= $conf->toDialplan() . "\n\n";
                }
            }

            $this->writeAsteriskFile($this->extensionsPath, $content);
            $this->reloadDialplan();
            $this->reloadPjsip();

            // Update features.conf for record opt-out
            $this->writeFeatures();

            Log::info('Dialplan written', ['flows' => $flows->count()]);
            return true;
        } catch (\Throwable $e) {
            Log::error('Failed to write dialplan', ['error' => $e->getMessage()]);
            return false;
        }
    }

    /**
     * Update the trunk's inbound PJSIP endpoint context to match the CallFlow.
     */
    private function syncTrunkContext(CallFlow $flow): void
    {
        $trunk = $flow->trunk;
        if (!$trunk) return;

        $inboundId = $trunk->getInboundEndpointId();
        $context = $flow->inbound_context;

        try {
            // Update ps_endpoints context for the inbound endpoint
            $updated = DB::connection($this->asteriskConn)
                ->table('ps_endpoints')
                ->where('id', $inboundId)
                ->update(['context' => $context]);

            if ($updated) {
                Log::info("Synced trunk inbound context", [
                    'trunk' => $trunk->name,
                    'endpoint' => $inboundId,
                    'context' => $context,
                ]);
            }

            // Also update the trunk model's inbound_context
            if ($trunk->inbound_context !== $context) {
                $trunk->update(['inbound_context' => $context]);
            }
        } catch (\Throwable $e) {
            Log::warning("Could not sync trunk context", ['error' => $e->getMessage()]);
        }
    }

    /**
     * Regenerate queues.conf with all enabled CallQueues.
     */
    public function writeQueues(): bool
    {
        try {
            $content = "[general]\n";
            $content .= "persistentmembers = yes\n";
            $content .= "autofill = yes\n";
            $content .= "shared_lastcall = yes\n\n";

            $queues = CallQueue::where('enabled', true)
                ->orderBy('name')
                ->get();

            foreach ($queues as $queue) {
                $content .= $queue->toQueuesConf() . "\n\n";
            }

            $this->writeAsteriskFile($this->queuesPath, $content);
            $this->reloadQueues();

            Log::info('Queues config written', ['queues' => $queues->count()]);
            return true;
        } catch (\Throwable $e) {
            Log::error('Failed to write queues config', ['error' => $e->getMessage()]);
            return false;
        }
    }

    /**
     * Generate features.conf with StopMixMonitor mappings for record opt-out.
     */
    public function writeFeatures(): bool
    {
        try {
            // Collect all unique opt-out keys from enabled flows
            $keys = CallFlow::where('enabled', true)
                ->where('record_calls', true)
                ->where('record_optout', true)
                ->pluck('record_optout_key')
                ->unique()
                ->filter()
                ->values();

            $content = "[general]\n";
            $content .= "; Features config — auto-generated by Voxa Center\n";
            $content .= "transferdigittimeout = 3\n";
            $content .= "atxfernoanswertimeout = 15\n";
            $content .= "atxferdropcall = no\n";
            $content .= "pickupexten = *8\n\n";

            $content .= "[featuremap]\n";
            $content .= "; Transfert aveugle : ## suivi du numero\n";
            $content .= "blindxfer => ##\n";
            $content .= "; Transfert assiste : *2 suivi du numero\n";
            $content .= "atxfer => *2\n";
            $content .= "; Deconnexion\n";
            $content .= "disconnect => *0\n\n";

            $content .= "[applicationmap]\n";
            $content .= "; Record opt-out: caller presses key to stop MixMonitor\n";

            foreach ($keys as $key) {
                $content .= "stoprecord_{$key} => {$key},self,StopMixMonitor,\n";
            }

            // Always include default key 8 if no flows use it
            if ($keys->isEmpty() || !$keys->contains('8')) {
                $content .= "stoprecord_8 => 8,self,StopMixMonitor,\n";
            }

            $this->writeAsteriskFile($this->featuresPath, $content);
            $this->reloadFeatures();

            Log::info('Features config written', ['optout_keys' => $keys->all()]);
            return true;
        } catch (\Throwable $e) {
            Log::error('Failed to write features config', ['error' => $e->getMessage()]);
            return false;
        }
    }

    /**
     * Generate confbridge.conf with bridge and user profiles.
     */
    public function writeConferences(): bool
    {
        try {
            $content = "; confbridge.conf — auto-generated by Voxa Center\n\n";

            // Default bridge profile
            $content .= "[default_bridge]\n";
            $content .= "type = bridge\n";
            $content .= "max_members = 50\n\n";

            // Default user profile
            $content .= "[default_user]\n";
            $content .= "type = user\n";
            $content .= "announce_join_leave = yes\n";
            $content .= "music_on_hold_when_empty = yes\n\n";

            $rooms = ConferenceRoom::where('enabled', true)->orderBy('name')->get();

            foreach ($rooms as $room) {
                $content .= $room->toBridgeProfile() . "\n\n";
                $content .= $room->toUserProfile() . "\n\n";
                if ($room->admin_pin) {
                    $content .= $room->toAdminProfile() . "\n\n";
                }
            }

            $this->writeAsteriskFile($this->confbridgePath, $content);

            exec('sudo /usr/sbin/asterisk -rx "module reload app_confbridge.so" 2>&1', $out, $code);
            if ($code !== 0) {
                Log::warning('ConfBridge reload failed', ['output' => implode("\n", $out)]);
            }

            Log::info('ConfBridge config written', ['rooms' => $rooms->count()]);
            return true;
        } catch (\Throwable $e) {
            Log::error('Failed to write confbridge config', ['error' => $e->getMessage()]);
            return false;
        }
    }

    /**
     * Write all configs.
     */
    public function writeAll(): bool
    {
        return $this->writeExtensions() && $this->writeQueues() && $this->writeFeatures() && $this->writeConferences();
    }

    /**
     * Get base dialplan (everything before the auto-generated marker).
     */
    private function getBaseDialplan(): string
    {
        if (!file_exists($this->extensionsPath)) {
            return $this->defaultBase();
        }

        $content = file_get_contents($this->extensionsPath);
        $pos = strpos($content, $this->marker);

        if ($pos !== false) {
            return rtrim(substr($content, 0, $pos));
        }

        return rtrim($content);
    }

    private function defaultBase(): string
    {
        return <<<'CONF'
[general]
static = yes
writeprotect = no
clearglobalvars = no

[from-internal]
include => conf-rooms
; Echo test
exten => 600,1,Answer()
 same => n,Playback(demo-echotest)
 same => n,Echo()
 same => n,Hangup()

exten => _X.,1,NoOp(Appel interne vers ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},30,tT)
 same => n,Hangup()

[from-trunk]
exten => _X.,1,NoOp(Appel entrant depuis trunk vers ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},30,tT)
 same => n,Hangup()
CONF;
    }

    /**
     * Write a file to /etc/asterisk/ using sudo tee (permission-safe).
     */
    private function writeAsteriskFile(string $path, string $content): void
    {
        $tmpFile = tempnam(sys_get_temp_dir(), 'ast_');
        file_put_contents($tmpFile, $content);

        exec(sprintf(
            'sudo /usr/bin/tee %s < %s > /dev/null 2>&1',
            escapeshellarg($path),
            escapeshellarg($tmpFile)
        ), $out, $code);

        unlink($tmpFile);

        if ($code !== 0) {
            throw new \RuntimeException("Failed to write {$path} via sudo tee (code {$code})");
        }
    }

    private function reloadDialplan(): void
    {
        exec('sudo /usr/sbin/asterisk -rx "dialplan reload" 2>&1', $out, $code);
        if ($code !== 0) {
            Log::warning('Dialplan reload failed', ['output' => implode("\n", $out)]);
        }
    }

    private function reloadPjsip(): void
    {
        // Regenerate static identify conf before reload
        app(SipProvisioningService::class)->writeIdentifyConf();

        exec('sudo /usr/sbin/asterisk -rx "pjsip reload" 2>&1', $out, $code);
        if ($code !== 0) {
            Log::warning('PJSIP reload failed', ['output' => implode("\n", $out)]);
        }
    }

    private function reloadQueues(): void
    {
        exec('sudo /usr/sbin/asterisk -rx "module reload app_queue.so" 2>&1', $out, $code);
        if ($code !== 0) {
            Log::warning('Queues reload failed', ['output' => implode("\n", $out)]);
        }
    }

    private function reloadFeatures(): void
    {
        exec('sudo /usr/sbin/asterisk -rx "features reload" 2>&1', $out, $code);
        if ($code !== 0) {
            Log::warning('Features reload failed', ['output' => implode("\n", $out)]);
        }
    }
}
