<?php

namespace App\Services;

use App\Models\CallFlow;
use App\Models\CallQueue;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use App\Services\SipProvisioningService;

class DialplanService
{
    private string $extensionsPath = '/etc/asterisk/extensions.conf';
    private string $queuesPath = '/etc/asterisk/queues.conf';
    private string $marker = '; === AUTO-GENERATED BY SIP.ctrl ===';
    private string $asteriskConn = 'asterisk';

    /**
     * Regenerate extensions.conf, sync trunk contexts, reload Asterisk.
     */
    public function writeExtensions(): bool
    {
        try {
            $content = $this->getBaseDialplan();
            $content .= "\n\n" . $this->marker . "\n";
            $content .= "; Ne pas editer — gere par le Call Flow Builder\n\n";

            $flows = CallFlow::with('trunk')
                ->where('enabled', true)
                ->orderBy('priority')
                ->orderBy('name')
                ->get();

            foreach ($flows as $flow) {
                if (!$flow->trunk) continue;

                // Sync the trunk inbound endpoint context in Asterisk Realtime DB
                $this->syncTrunkContext($flow);

                $content .= $flow->toDialplan() . "\n\n";
            }

            $this->writeAsteriskFile($this->extensionsPath, $content);
            $this->reloadDialplan();
            $this->reloadPjsip();

            Log::info('Dialplan written', ['flows' => $flows->count()]);
            return true;
        } catch (\Throwable $e) {
            Log::error('Failed to write dialplan', ['error' => $e->getMessage()]);
            return false;
        }
    }

    /**
     * Update the trunk's inbound PJSIP endpoint context to match the CallFlow.
     */
    private function syncTrunkContext(CallFlow $flow): void
    {
        $trunk = $flow->trunk;
        if (!$trunk) return;

        $inboundId = $trunk->getInboundEndpointId();
        $context = $flow->inbound_context;

        try {
            // Update ps_endpoints context for the inbound endpoint
            $updated = DB::connection($this->asteriskConn)
                ->table('ps_endpoints')
                ->where('id', $inboundId)
                ->update(['context' => $context]);

            if ($updated) {
                Log::info("Synced trunk inbound context", [
                    'trunk' => $trunk->name,
                    'endpoint' => $inboundId,
                    'context' => $context,
                ]);
            }

            // Also update the trunk model's inbound_context
            if ($trunk->inbound_context !== $context) {
                $trunk->update(['inbound_context' => $context]);
            }
        } catch (\Throwable $e) {
            Log::warning("Could not sync trunk context", ['error' => $e->getMessage()]);
        }
    }

    /**
     * Regenerate queues.conf with all enabled CallQueues.
     */
    public function writeQueues(): bool
    {
        try {
            $content = "[general]\n";
            $content .= "persistentmembers = yes\n";
            $content .= "autofill = yes\n";
            $content .= "shared_lastcall = yes\n\n";

            $queues = CallQueue::where('enabled', true)
                ->orderBy('name')
                ->get();

            foreach ($queues as $queue) {
                $content .= $queue->toQueuesConf() . "\n\n";
            }

            $this->writeAsteriskFile($this->queuesPath, $content);
            $this->reloadQueues();

            Log::info('Queues config written', ['queues' => $queues->count()]);
            return true;
        } catch (\Throwable $e) {
            Log::error('Failed to write queues config', ['error' => $e->getMessage()]);
            return false;
        }
    }

    /**
     * Write both configs.
     */
    public function writeAll(): bool
    {
        return $this->writeExtensions() && $this->writeQueues();
    }

    /**
     * Get base dialplan (everything before the auto-generated marker).
     */
    private function getBaseDialplan(): string
    {
        if (!file_exists($this->extensionsPath)) {
            return $this->defaultBase();
        }

        $content = file_get_contents($this->extensionsPath);
        $pos = strpos($content, $this->marker);

        if ($pos !== false) {
            return rtrim(substr($content, 0, $pos));
        }

        return rtrim($content);
    }

    private function defaultBase(): string
    {
        return <<<'CONF'
[general]
static = yes
writeprotect = no
clearglobalvars = no

[from-internal]
exten => _X.,1,NoOp(Appel interne vers ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},30,tT)
 same => n,Hangup()

[from-trunk]
exten => _X.,1,NoOp(Appel entrant depuis trunk vers ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},30,tT)
 same => n,Hangup()
CONF;
    }

    /**
     * Write a file to /etc/asterisk/ using sudo tee (permission-safe).
     */
    private function writeAsteriskFile(string $path, string $content): void
    {
        $tmpFile = tempnam(sys_get_temp_dir(), 'ast_');
        file_put_contents($tmpFile, $content);

        exec(sprintf(
            'sudo /usr/bin/tee %s < %s > /dev/null 2>&1',
            escapeshellarg($path),
            escapeshellarg($tmpFile)
        ), $out, $code);

        unlink($tmpFile);

        if ($code !== 0) {
            throw new \RuntimeException("Failed to write {$path} via sudo tee (code {$code})");
        }
    }

    private function reloadDialplan(): void
    {
        exec('sudo /usr/sbin/asterisk -rx "dialplan reload" 2>&1', $out, $code);
        if ($code !== 0) {
            Log::warning('Dialplan reload failed', ['output' => implode("\n", $out)]);
        }
    }

    private function reloadPjsip(): void
    {
        // Regenerate static identify conf before reload
        app(SipProvisioningService::class)->writeIdentifyConf();

        exec('sudo /usr/sbin/asterisk -rx "pjsip reload" 2>&1', $out, $code);
        if ($code !== 0) {
            Log::warning('PJSIP reload failed', ['output' => implode("\n", $out)]);
        }
    }

    private function reloadQueues(): void
    {
        exec('sudo /usr/sbin/asterisk -rx "module reload app_queue.so" 2>&1', $out, $code);
        if ($code !== 0) {
            Log::warning('Queues reload failed', ['output' => implode("\n", $out)]);
        }
    }
}
