<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class CallFlow extends Model
{
    protected $fillable = [
        'name', 'description', 'trunk_id', 'inbound_context',
        'steps', 'positions', 'enabled', 'priority', 'created_by',
    ];

    protected $casts = [
        'steps'     => 'array',
        'positions' => 'array',
        'enabled'   => 'boolean',
    ];

    public function trunk(): BelongsTo
    {
        return $this->belongsTo(Trunk::class);
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * Generate Asterisk extensions.conf dialplan from the visual steps.
     */
    public function toDialplan(): string
    {
        $ctx = $this->inbound_context;
        $lines = [];
        $lines[] = "[{$ctx}]";
        $lines[] = "; Auto-generated by CallFlow: {$this->name}";

        // Main entry: match any number
        $priority = 1;
        $lines[] = "exten => _X.,{$priority},NoOp(=== CallFlow [{$this->name}] from \${CALLERID(num)} ===)";
        $priority++;
        $lines[] = " same => n,Set(CDR(direction)=inbound)";
        $lines[] = " same => n,Set(CDR(trunk)={$this->trunk->name})";

        // Auto-answer if no explicit answer step before first action
        $hasAnswer = collect($this->steps)->contains(fn($s) => ($s['type'] ?? '') === 'answer');
        if (!$hasAnswer) {
            $lines[] = " same => n,Ringing()";
            $lines[] = " same => n,Wait(1)";
            $lines[] = " same => n,Answer()";
        }

        foreach ($this->steps as $step) {
            $type = $step['type'] ?? '';

            switch ($type) {
                case 'answer':
                    $lines[] = " same => n,Ringing()";
                    $lines[] = " same => n,Wait(" . ($step['wait'] ?? 1) . ")";
                    $lines[] = " same => n,Answer()";
                    break;

                case 'playback':
                    $sound = $step['sound'] ?? 'hello-world';
                    $lines[] = " same => n,Playback({$sound})";
                    break;

                case 'queue':
                    $queueName = $step['queue_name'] ?? 'default';
                    $timeout = $step['timeout'] ?? 60;
                    $lines[] = " same => n,Queue({$queueName},tT,,,{$timeout})";
                    break;

                case 'ring':
                    $extensions = $step['extensions'] ?? [];
                    $timeout = $step['timeout'] ?? 25;
                    if (!empty($extensions)) {
                        $dialTargets = implode('&', array_map(fn($e) => "PJSIP/{$e}", $extensions));
                        $lines[] = " same => n,Dial({$dialTargets},{$timeout},tTm(default))";
                        // If answered, hangup cleanly; otherwise continue scenario
                        $lines[] = " same => n,GotoIf(\$[\"\${DIALSTATUS}\" = \"ANSWER\"]?hangup)";
                        $lines[] = " same => n,NoOp(Dial failed: \${DIALSTATUS} — continuing scenario)";
                    }
                    break;

                case 'voicemail':
                    $box = $step['mailbox'] ?? '1000';
                    $type = $step['vm_type'] ?? 'u';
                    $lines[] = " same => n,VoiceMail({$box}@default,{$type})";
                    break;

                case 'hangup':
                    $lines[] = " same => n,Hangup()";
                    break;

                case 'goto':
                    $target = $step['target_context'] ?? 'default';
                    $lines[] = " same => n,Goto({$target},\${EXTEN},1)";
                    break;

                case 'moh':
                    $class = $step['moh_class'] ?? 'default';
                    $duration = $step['duration'] ?? 10;
                    $lines[] = " same => n,MusicOnHold({$class},{$duration})";
                    break;

                case 'announcement':
                    $sound = $step['sound'] ?? 'custom/welcome';
                    $lines[] = " same => n,Playback({$sound})";
                    break;

                case 'time_condition':
                    $lines[] = " same => n,NoOp(Time condition: " . ($step['label'] ?? 'check') . ")";
                    break;
            }
        }

        // Ensure hangup label at the end (target for GotoIf after successful Dial)
        $lines[] = " same => n(hangup),Hangup()";


        // Also add catch-all patterns
        $lines[] = "";
        $lines[] = "exten => _+X.,1,Goto({$ctx},\${EXTEN:1},1)";
        $lines[] = "exten => s,1,Goto({$ctx},0000,1)";

        return implode("\n", $lines);
    }
}
