<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class CallFlow extends Model
{
    protected $fillable = [
        'name', 'description', 'trunk_id', 'inbound_context',
        'steps', 'positions', 'enabled', 'record_calls',
        'record_optout', 'record_optout_key', 'caller_id_filter',
        'did_filter', 'priority', 'created_by',
    ];

    protected $casts = [
        'steps'            => 'array',
        'positions'        => 'array',
        'caller_id_filter' => 'array',
        'did_filter'       => 'array',
        'enabled'          => 'boolean',
        'record_calls'     => 'boolean',
        'record_optout'    => 'boolean',
    ];

    public function trunk(): BelongsTo
    {
        return $this->belongsTo(Trunk::class);
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * Build the AGI(piper-tts.sh, ...) line for a given voice key.
     * Voice map mirrors TtsController::$voices (siwis/jessica/pierre/tom).
     */
    private function piperAgiLine(string $text, ?string $voice): string
    {
        $map = [
            'siwis'   => ['model' => 'fr_FR-siwis-medium'],
            'jessica' => ['model' => 'fr_FR-upmc-medium', 'speaker' => 0],
            'pierre'  => ['model' => 'fr_FR-upmc-medium', 'speaker' => 1],
            'tom'     => ['model' => 'fr_FR-tom-medium'],
        ];
        $cfg = $map[$voice] ?? $map['siwis'];
        $args = '"' . addslashes($text) . '",' . $cfg['model'];
        if (isset($cfg['speaker'])) {
            $args .= ',' . $cfg['speaker'];
        }
        return " same => n,AGI(piper-tts.sh,{$args})";
    }

    /**
     * Generate Asterisk extensions.conf dialplan from the visual steps.
     */
    public function toDialplan(): string
    {
        $ctx = $this->inbound_context;
        $lines = [];
        $lines[] = "[{$ctx}]";
        $lines[] = "; Auto-generated by CallFlow: {$this->name}";

        // Main entry: match any number
        $priority = 1;
        $lines[] = "exten => _X.,{$priority},NoOp(=== CallFlow [{$this->name}] from \${CALLERID(num)} ===)";
        $priority++;
        $lines[] = " same => n,Set(CDR(direction)=inbound)";
        $lines[] = " same => n,Set(CDR(trunk)={$this->trunk->name})";

        // Recording opt-out feature name
        $optoutKey = $this->record_optout_key ?: '8';
        $featureName = "stoprecord_{$optoutKey}";

        // Auto-answer if no explicit answer step before first action
        $hasAnswer = collect($this->steps)->contains(fn($s) => ($s['type'] ?? '') === 'answer');
        if (!$hasAnswer) {
            $lines[] = " same => n,Ringing()";
            $lines[] = " same => n,Wait(1)";
            $lines[] = " same => n,Answer()";
            if ($this->record_calls) {
                $lines[] = " same => n,MixMonitor(\${UNIQUEID}.wav,b)";
                if ($this->record_optout) {
                    $lines[] = " same => n,Set(DYNAMIC_FEATURES={$featureName})";
                }
                $recordInserted = true;
            }
        }

        // Call recording via MixMonitor
        $recordInserted = false;

        $ivrExtensions = []; // IVR sub-extensions to add at end

        foreach ($this->steps as $stepIndex => $step) {
            $type = $step['type'] ?? '';

            switch ($type) {
                case 'answer':
                    $lines[] = " same => n,Ringing()";
                    $lines[] = " same => n,Wait(" . ($step['wait'] ?? 1) . ")";
                    $lines[] = " same => n,Answer()";
                    if ($this->record_calls && !$recordInserted) {
                        $lines[] = " same => n,MixMonitor(\${UNIQUEID}.wav,b)";
                        if ($this->record_optout) {
                            $lines[] = " same => n,Set(DYNAMIC_FEATURES={$featureName})";
                        }
                        $recordInserted = true;
                    }
                    break;

                case 'playback':
                    $ttsText = $step['tts_text'] ?? '';
                    if (!empty($ttsText)) {
                        $lines[] = $this->piperAgiLine($ttsText, $step['tts_voice'] ?? 'siwis');
                    } else {
                        $sound = $step['sound'] ?? 'hello-world';
                        $lines[] = " same => n,Playback({$sound})";
                    }
                    break;

                case 'queue':
                    $queueName = $step['queue_name'] ?? 'default';
                    $timeout = $step['timeout'] ?? 60;
                    $lines[] = " same => n,Queue({$queueName},tT,,,{$timeout})";
                    break;

                case 'ring':
                    $extensions = $step['extensions'] ?? [];
                    $timeout = $step['timeout'] ?? 25;
                    if (!empty($extensions)) {
                        $dialTargets = implode('&', array_map(fn($e) => "PJSIP/{$e}", $extensions));
                        $lines[] = " same => n,Dial({$dialTargets},{$timeout},tTm(default))";
                        // If answered, hangup cleanly; otherwise continue scenario
                        $lines[] = " same => n,GotoIf(\$[\"\${DIALSTATUS}\" = \"ANSWER\"]?hangup)";
                        $lines[] = " same => n,NoOp(Dial failed: \${DIALSTATUS} — continuing scenario)";
                    }
                    break;

                case 'forward':
                    $destType = $step['dest_type'] ?? 'extension';
                    $destination = $step['destination'] ?? '';
                    $timeout = $step['timeout'] ?? 20;
                    if ($destination !== '') {
                        if ($destType === 'extension') {
                            $target = "PJSIP/{$destination}";
                        } else {
                            $trunk = \App\Models\Trunk::where('status', 'online')->first();
                            $trunkId = $trunk ? $trunk->getAsteriskEndpointId() : 'trunk';
                            $target = "PJSIP/{$destination}@{$trunkId}";
                        }
                        $lines[] = " same => n,Dial({$target},{$timeout},tTm(default))";
                        $lines[] = " same => n,GotoIf(\$[\"\${DIALSTATUS}\" = \"ANSWER\"]?hangup)";
                        $lines[] = " same => n,NoOp(Forward to {$destination} failed: \${DIALSTATUS} — continuing)";
                    }
                    break;

                case 'voicemail':
                    $box = $step['mailbox'] ?? '1000';
                    $type = $step['vm_type'] ?? 'u';
                    $lines[] = " same => n,VoiceMail({$box}@default,{$type})";
                    break;

                case 'hangup':
                    $lines[] = " same => n,Hangup()";
                    break;

                case 'goto':
                    $target = $step['target_context'] ?? 'default';
                    $lines[] = " same => n,Goto({$target},\${EXTEN},1)";
                    break;

                case 'moh':
                    $class = $step['moh_class'] ?? 'default';
                    $duration = $step['duration'] ?? 10;
                    $lines[] = " same => n,MusicOnHold({$class},{$duration})";
                    break;

                case 'announcement':
                    $ttsText = $step['tts_text'] ?? '';
                    if (!empty($ttsText)) {
                        $lines[] = $this->piperAgiLine($ttsText, $step['tts_voice'] ?? 'siwis');
                    } else {
                        $sound = $step['sound'] ?? 'custom/welcome';
                        $lines[] = " same => n,Playback({$sound})";
                    }
                    break;

                case 'ivr':
                    $sound = $step['sound'] ?? 'custom/menu';
                    $ttsText = $step['tts_text'] ?? '';
                    $timeout = $step['timeout'] ?? 5;
                    $maxLoops = $step['max_loops'] ?? 3;
                    $options = $step['options'] ?? [];
                    $branchTargets = $step['branch_targets'] ?? [];
                    $ivrLabel = 'ivr_' . $stepIndex;

                    // Loop: set counter, save extension for Goto, play message, wait for DTMF
                    $lines[] = " same => n,Set(IVR_LOOPS=0)";
                    $lines[] = " same => n,Set(IVR_EXTEN=\${EXTEN})";
                    $lines[] = " same => n({$ivrLabel}),Set(IVR_LOOPS=\$[\${IVR_LOOPS}+1])";
                    $lines[] = " same => n,GotoIf(\$[\${IVR_LOOPS} > {$maxLoops}]?{$ivrLabel}_end)";
                    if (!empty($ttsText)) {
                        // Pre-generate TTS audio file for use with Background()
                        $voice = $step['tts_voice'] ?? 'siwis';
                        $voiceMap = ['siwis' => 'fr_FR-siwis-medium', 'upmc' => 'fr_FR-upmc-medium', 'mls' => 'fr_FR-mls-medium'];
                        $voiceModel = $voiceMap[$voice] ?? $voiceMap['siwis'];
                        $ttsHash = md5("{$voiceModel}:{$ttsText}");
                        $ttsFile = "tts/{$ttsHash}";

                        // Generate the file on disk if not exists
                        $sndDir = '/var/lib/asterisk/sounds/tts';
                        $cacheDir = '/var/spool/asterisk/tts_cache';
                        if (!file_exists("{$sndDir}/{$ttsHash}.sln")) {
                            @mkdir($sndDir, 0755, true);
                            @mkdir($cacheDir, 0755, true);
                            $wavTmp = "{$cacheDir}/{$ttsHash}.wav";
                            $piperBin = '/opt/piper/piper/piper';
                            $modelPath = "/opt/piper/models/{$voiceModel}.onnx";
                            $proc = proc_open([$piperBin, '--model', $modelPath, '--output_file', $wavTmp],
                                [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes);
                            if (is_resource($proc)) {
                                fwrite($pipes[0], $ttsText); fclose($pipes[0]); fclose($pipes[1]); fclose($pipes[2]);
                                proc_close($proc);
                                exec("sox {$wavTmp} -r 8000 -c 1 -e signed-integer -b 16 {$sndDir}/{$ttsHash}.sln 2>/dev/null");
                                @unlink($wavTmp);
                            }
                        }
                        $lines[] = " same => n,Background({$ttsFile})";
                    } else {
                        $lines[] = " same => n,Background({$sound})";
                    }
                    // Set CHANNEL(dtmf_features) and digit timeout for single-digit IVR
                    $lines[] = " same => n,Set(TIMEOUT(digit)=1)";
                    $lines[] = " same => n,WaitExten({$timeout})";

                    // Generate IVR option extensions (DTMF keys)
                    foreach ($options as $key => $dest) {
                        $ivrLines = [];
                        $ivrLines[] = "exten => {$key},1,NoOp(IVR touche {$key})";

                        // Check if this key has a branch target (visual connection to a block)
                        $targetNodeId = $branchTargets[$key] ?? null;

                        // Follow the chain of blocks from the target
                        $chainSteps = [];
                        if ($targetNodeId) {
                            $visited = [];
                            $currentNodeId = $targetNodeId;
                            while ($currentNodeId && !in_array($currentNodeId, $visited)) {
                                $visited[] = $currentNodeId;
                                foreach ($this->steps as $s) {
                                    if (($s['_nodeId'] ?? null) == $currentNodeId) {
                                        $chainSteps[] = $s;
                                        // Find next node in chain (linear next)
                                        $idx = array_search($s, $this->steps);
                                        $nextStep = $this->steps[$idx + 1] ?? null;
                                        // Only follow if next step is not a branch target of another key
                                        $isOtherTarget = false;
                                        foreach ($branchTargets as $bk => $bt) {
                                            if ($bk !== $key && $bt == ($nextStep['_nodeId'] ?? -1)) {
                                                $isOtherTarget = true;
                                            }
                                        }
                                        $currentNodeId = (!$isOtherTarget && $nextStep) ? ($nextStep['_nodeId'] ?? null) : null;
                                        break;
                                    }
                                }
                            }
                        }

                        $targetStep = $chainSteps[0] ?? null;

                        if (!empty($chainSteps)) {
                            // Generate inline dialplan for each block in the chain
                            foreach ($chainSteps as $targetStep) {
                            $targetType = $targetStep['type'] ?? '';
                            switch ($targetType) {
                                case 'ring':
                                    $exts = $targetStep['extensions'] ?? [];
                                    $to = $targetStep['timeout'] ?? 25;
                                    if (!empty($exts)) {
                                        $targets = implode('&', array_map(fn($e) => "PJSIP/{$e}", $exts));
                                        $ivrLines[] = " same => n,Dial({$targets},{$to},tTm(default))";
                                    }
                                    break;
                                case 'queue':
                                    $ivrLines[] = " same => n,Queue(" . ($targetStep['queue_name'] ?? 'default') . ",tT,,,60)";
                                    break;
                                case 'moh':
                                    $ivrLines[] = " same => n,MusicOnHold(" . ($targetStep['moh_class'] ?? 'default') . "," . ($targetStep['duration'] ?? 10) . ")";
                                    break;
                                case 'voicemail':
                                    $ivrLines[] = " same => n,VoiceMail(" . ($targetStep['mailbox'] ?? '1000') . "@default," . ($targetStep['vm_type'] ?? 'u') . ")";
                                    break;
                                case 'forward':
                                    $fwdDest = $targetStep['destination'] ?? '';
                                    if ($fwdDest) {
                                        $fwdType = $targetStep['dest_type'] ?? 'extension';
                                        if ($fwdType === 'extension') {
                                            $ivrLines[] = " same => n,Dial(PJSIP/{$fwdDest}," . ($targetStep['timeout'] ?? 20) . ",tTm(default))";
                                        } else {
                                            $trunk = \App\Models\Trunk::where('status', 'online')->first();
                                            $trunkId = $trunk ? $trunk->getAsteriskEndpointId() : 'trunk';
                                            $ivrLines[] = " same => n,Dial(PJSIP/{$fwdDest}@{$trunkId}," . ($targetStep['timeout'] ?? 20) . ",tTm(default))";
                                        }
                                    }
                                    break;
                                case 'ai_agent':
                                    $aiP = $targetStep['ai_prompt'] ?? 'Assistant telephonique';
                                    $aiC = $targetStep['ai_context'] ?? '';
                                    $aiR = $targetStep['ai_rag_folder'] ?? '';
                                    if (!empty($aiC)) $aiP .= "\n\nINFORMATIONS COMPLEMENTAIRES:\n" . $aiC;
                                    $aiV = $targetStep['ai_voice'] ?? 'coral';
                                    $pSafe = str_replace(["\n","\r"], ['\\n',''], addslashes($aiP));
                                    $ivrLines[] = " same => n,System(echo '{$pSafe}' > /tmp/ai_prompt_\${UNIQUEID}.txt)";
                                    $ivrLines[] = " same => n,System(echo '{$aiV}' > /tmp/ai_voice_\${UNIQUEID}.txt)";
                                    $ivrLines[] = " same => n,System(echo '{$aiR}' > /tmp/ai_rag_\${UNIQUEID}.txt)";
                                    $ivrLines[] = " same => n,AudioSocket(\${UUID()},127.0.0.1:9092)";
                                    break;
                                case 'playback':
                                case 'announcement':
                                    $tts = $targetStep['tts_text'] ?? '';
                                    if (!empty($tts)) {
                                        $ivrLines[] = $this->piperAgiLine($tts, $targetStep['tts_voice'] ?? 'siwis');
                                    } else {
                                        $ivrLines[] = " same => n,Playback(" . ($targetStep['sound'] ?? 'hello-world') . ")";
                                    }
                                    break;
                                case 'hangup':
                                    break;
                            }
                            } // end foreach chainSteps
                        } elseif (!empty($dest)) {
                            // Legacy: text destination
                            if (preg_match('/^\d{3,}$/', $dest)) {
                                $ivrLines[] = " same => n,Dial(PJSIP/{$dest},25,tTm(default))";
                            } elseif (str_starts_with($dest, 'queue-') || str_starts_with($dest, 'q-')) {
                                $ivrLines[] = " same => n,Queue({$dest},tT,,,60)";
                            } else {
                                $ivrLines[] = " same => n,Dial(PJSIP/{$dest},25,tTm(default))";
                            }
                        }
                        $ivrLines[] = " same => n,Hangup()";
                        $ivrExtensions[] = implode("\n", $ivrLines);
                    }

                    // Invalid key → play error + replay menu (use saved extension)
                    $ivrExtensions[] = "exten => i,1,Playback(custom/invalid)\n same => n,Goto({$ctx},\${IVR_EXTEN},{$ivrLabel})";
                    // Timeout → loop back
                    $ivrExtensions[] = "exten => t,1,Goto({$ctx},\${IVR_EXTEN},{$ivrLabel})";

                    // End of loops (no valid input after max retries) → goodbye
                    $lines[] = " same => n({$ivrLabel}_end),NoOp(IVR max retries reached)";
                    $lines[] = " same => n,Playback(custom/goodbye)";
                    break;

                case 'ai_agent':
                    $aiPrompt = $step['ai_prompt'] ?? 'Tu es un assistant telephonique professionnel. Reponds en francais.';
                    $aiContext = $step['ai_context'] ?? '';
                    $aiRagFolder = $step['ai_rag_folder'] ?? '';
                    if (!empty($aiContext)) {
                        $aiPrompt .= "\n\nINFORMATIONS COMPLEMENTAIRES:\n" . $aiContext;
                    }
                    $aiVoice = $step['ai_voice'] ?? 'coral';
                    // Write prompt to temp file so AudioSocket server can read it
                    $lines[] = " same => n,NoOp(=== OpenAI Realtime Agent ===)";
                    $lines[] = " same => n,Set(AI_RAG={$aiRagFolder})";
                    $promptSafe = str_replace(["\n", "\r"], ['\n', ''], addslashes($aiPrompt));
                    $lines[] = " same => n,System(echo '{$promptSafe}' > /tmp/ai_prompt_\${UNIQUEID}.txt)";
                    $lines[] = " same => n,System(echo '{$aiVoice}' > /tmp/ai_voice_\${UNIQUEID}.txt)";
                    $lines[] = " same => n,System(echo '{$aiRagFolder}' > /tmp/ai_rag_\${UNIQUEID}.txt)";
                    $lines[] = " same => n,AudioSocket(\${UUID()},127.0.0.1:9092)";
                    $lines[] = " same => n,System(rm -f /tmp/ai_prompt_\${UNIQUEID}.txt /tmp/ai_voice_\${UNIQUEID}.txt /tmp/ai_rag_\${UNIQUEID}.txt)";
                    break;

                case 'did_filter':
                    $matchNumber = $step['match_number'] ?? '';
                    $branchTargets = $step['branch_targets'] ?? [];
                    $dfLabel = 'df_' . $stepIndex;

                    $lines[] = " same => n,NoOp(DID Filter: {$matchNumber})";
                    if ($matchNumber) {
                        $lines[] = " same => n,GotoIf(\$[\"\${EXTEN}\" = \"{$matchNumber}\"]?{$dfLabel}_match)";
                    } else {
                        $lines[] = " same => n,Goto({$dfLabel}_match)";
                    }

                    // No match branch
                    $lines[] = " same => n,NoOp(DID No Match)";
                    $lines[] = " same => n,Hangup()";
                    // Match branch
                    $lines[] = " same => n({$dfLabel}_match),NoOp(DID Match — on continue)";
                    break;

                case 'cid_filter':
                    $matchNumber = $step['match_number'] ?? '';
                    $branchTargets = $step['branch_targets'] ?? [];
                    $cfLabel = 'cf_' . $stepIndex;

                    $lines[] = " same => n,NoOp(CID Filter: {$matchNumber})";
                    if ($matchNumber) {
                        $lines[] = " same => n,GotoIf(\$[\"\${CALLERID(num)}\" = \"{$matchNumber}\"]?{$cfLabel}_match)";
                    } else {
                        $lines[] = " same => n,Goto({$cfLabel}_match)";
                    }

                    // No match branch
                    $lines[] = " same => n,NoOp(CID No Match)";
                    $lines[] = " same => n,Hangup()";
                    // Match branch
                    $lines[] = " same => n({$cfLabel}_match),NoOp(CID Match — on continue)";
                    break;

                case 'time_condition':
                    $timeStart = $step['time_start'] ?? '09:00';
                    $timeEnd   = $step['time_end'] ?? '18:00';
                    $days      = $step['days'] ?? 'mon-fri';
                    $branchTargets = $step['branch_targets'] ?? [];

                    $dayMap = [
                        'mon-fri' => 'mon-fri',
                        'mon-sat' => 'mon-sat',
                        'mon-sun' => '*',
                        'sat-sun' => 'sat-sun',
                    ];
                    $astDays = $dayMap[$days] ?? $days;

                    $tcLabel = 'tc_' . $stepIndex;

                    $lines[] = " same => n,NoOp(Horaires: {$timeStart}-{$timeEnd} {$astDays})";
                    $lines[] = " same => n,GotoIfTime({$timeStart}-{$timeEnd},{$astDays},*,*?{$tcLabel}_open)";

                    // Closed branch: if branch_targets has 'closed', the visual branch handles it
                    // Otherwise fallback to legacy inline behavior
                    if (empty($branchTargets)) {
                        $closedAction = $step['closed_action'] ?? 'voicemail';
                        $closedSound  = $step['closed_sound'] ?? '';
                        $closedTarget = $step['closed_target'] ?? '1000';
                        if ($closedSound) {
                            $lines[] = " same => n,Answer()";
                            $lines[] = " same => n,Playback({$closedSound})";
                        }
                        if ($closedAction === 'voicemail') {
                            $lines[] = " same => n,VoiceMail({$closedTarget}@default,u)";
                        }
                        $lines[] = " same => n,Hangup()";
                        // Open: continue to next steps
                        $lines[] = " same => n({$tcLabel}_open),NoOp(Ouvert — on continue)";
                    } else {
                        // Closed: handled by visual branch → just hangup here (the branch node will handle)
                        $lines[] = " same => n,NoOp(Ferme — branche vers bloc suivant)";
                        $lines[] = " same => n,Hangup()";
                        // Open: continue to next steps
                        $lines[] = " same => n({$tcLabel}_open),NoOp(Ouvert — on continue)";
                    }
                    break;
            }
        }

        // Ensure hangup label at the end (target for GotoIf after successful Dial)
        $lines[] = " same => n(hangup),Hangup()";

        // IVR sub-extensions (DTMF options)
        if (!empty($ivrExtensions)) {
            $lines[] = "";
            $lines[] = "; IVR options";
            foreach ($ivrExtensions as $ivrExt) {
                $lines[] = $ivrExt;
            }
        }

        // Also add catch-all patterns
        $lines[] = "";
        $lines[] = "exten => _+X.,1,Goto({$ctx},\${EXTEN:1},1)";
        $lines[] = "exten => s,1,Goto({$ctx},0000,1)";

        return implode("\n", $lines);
    }
}
