[Definition]
failregex = NOTICE.* Request from .* failed for '<HOST>(:\d+)?' .* - No matching endpoint found
            NOTICE.* Request from .* failed for '<HOST>(:\d+)?' .* - Failed to authenticate
ignoreregex =
