[general]
static = yes
writeprotect = no
clearglobalvars = no

[from-internal]
exten => _X.,1,NoOp(Appel interne vers ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},30,tT)
 same => n,Hangup()

[from-trunk]
exten => _X.,1,NoOp(Appel entrant depuis trunk vers ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},30,tT)
 same => n,Hangup()
