[general]
format = wav49|wav
serveremail = voicemail@sip.local
attach = yes
maxmsg = 100
maxsecs = 300
minsecs = 3
maxgreet = 60
skipms = 3000
maxsilence = 10
silencethreshold = 128

[default]
; Boites vocales gerees par l'interface Laravel
; Format: extension => password,nom,email,pager,options
0033185090002 => 1234,OVH Principal,admin@sip.local,,tz=fr|attach=yes|saycid=yes|envelope=yes|delete=no
