[asterisk-sip]
enabled  = true
filter   = asterisk-sip
logpath  = /var/log/asterisk/messages
maxretry = 5
findtime = 300
bantime  = 600
action   = iptables-allports[name=asterisk-sip, protocol=all]
ignoreip = 127.0.0.1/8 91.121.128.0/23
